{% set name = "entropy" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "v{{ version }}"

source:
  url: https://github.com/raphaelvallat/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 63e91173b837002ce4b6cd4c42763aa998d78cb3ca48c297f4bb6adac813f902
       
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  
requirements:
  host:
    - pip
    - python
    - numpy
    - scipy
    - scikit-learn
    - numba

  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - numba

test:
  imports:
    - {{ name|lower }}
  requires:
    - pytest

about:
  home: https://raphaelvallat.com/entropy/build/html/index.html
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "EntroPy: EntroPy is a Python 3 package providing several time-efficient algorithms for computing the complexity of one-dimensional time series. It can be used for example to extract features from EEG signals."
  doc_url: "https://raphaelvallat.com/entropy/build/html/index.html"
  dev_url: "https://github.com/raphaelvallat/entropy/"

extra:
  recipe-maintainers:
    - PackageCondaDataScience
