travis:
  secure:
    BINSTAR_TOKEN: jv25bWglh1fSe20sawtG4myxrHN4fBJhE3gpzSdI+mj0yJvMFktIWfS9ViALZ45XTeeL2kdA/Yzldor3T7HTEpkwhUK02YgE6uubE2M8BwiNXPy4kJ9LX8aIePddRmB2v2uRDG5SShWXVOhzLL6DysbDgnjJch4tOU6A3hpFCIUVCdTuE96vHu8q9j2J+Qbu79Qm7F4Al0gnO/bjJK6doY8qSHyHhhiqcO8352cfXLrNfZ/vBW4URFv9NMZYya3lkZ3D1yhM3ccA5u9GVOTocTlDwyf/4Mym4SbWXqWN41u23FC6cH5sPVogVttFZ2ZJQle/NSfPZ1bGbe2Lkv9q6H+PgS37jFMGPS0K9J6nEQjFOiSta/JPjl2WIlRHOBCjiJaX/hTCSqG9ENO68k33VMMEMaQonH7rPgMRuKF7fP6ZYOlWnb39gDYdflv7qKGzOjxurMABapNJunQN3XilppGs6Q8R7/Pk/8xqyxZ0wQj2CZJwWEKjfEERlEkn5zvcQ7b6KLN4kt5aUsDWNurd7B8A66giZKrWBEtiRIHS7wnpNEOf3JbiETtyfNWZcYeWHnZV6VQCD5xNe4asgymFeNdYBClFcPkOnwnTwWph5QAsjnsl7j/XNEzPSFVweQy10p8tosvzGlG1T4SFi3niV4JmD2PvjZuZgKEBaUnAtnU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
